# Generated by Django 4.0.6 on 2022-07-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='user',
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
